name: deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy to DigitalOcean
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_IP }}
          username: ${{ secrets.DROPLET_USERNAME }}
          script: |
            cd ~/project-setup-team-wilmington-circuit/
            git checkout master
            git pull
            pm2 start npm -- start