name: deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to DigitalOcean
        uses: fifsky/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_IP }}
          user: gitdeploy
          pass: ${{ secrets.DEPLOY_PASSWORD }}
          command: |
            cd ~/project-setup-team-wilmington-circuit/
            git checkout master
            git pull
            pm2 start npm -- start
